name: Check-commit-messages-workflow

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  Check-commit-messages:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Check the commit message(s)
        uses: mristin/opinionated-commit-message@v2.3.2

      - name: READ HERE ON FAILURE FOR MORE INSTRUCTIONS
        if: ${{ failure() }}
        run: |
          Write-Host (
            "The title and the description of your pull request do not fit our style guide. " +
            "Please inspect carefully the error messages above and edit the pull request. " +
            "Since we are always squashing before merge, you can leave the commit messages as-are."
          )
